flasher:
  default: template
  # root_scripts:
  #   - 'https://cdn.jsdelivr.net/npm/@flasher/flasher@0.1.3/dist/flasher.min.js'
  template_factory:
      default: bootstrap
      templates:
          tailwindcss:
              view: '@FlasherSymfony/tailwindcss.html.twig'
              styles:
                - 'https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.1.1/base.min.css'
                - 'https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.1.1/utilities.css'
          tailwindcss_bg:
              view: '@FlasherSymfony/tailwindcss_bg.html.twig'
              styles:
                - 'https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.1.1/base.min.css'
                - 'https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.1.1/utilities.css'
          bootstrap:
              view: '@FlasherSymfony/bootstrap.html.twig'
              styles:
                - 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.3/css/bootstrap.min.css'
  auto_create_from_session: true
  types_mapping:
      success:
        - success
      error:
        - error
        - danger
      warning:
        - warning
        - alarm
      info:
        - info
        - notice
        - alert
