version: '3.1'

services:
  database:
    image: mysql:8
    environment:
      MYSQL_USER: main
      MYSQL_PASSWORD: main
      MYSQL_DATABASE: main_db
      MYSQL_ROOT_PASSWORD: main
    ports:
      - 6603:3306
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ../var/log:/var/log/mysql
